#!/usr/bin/env python

"""
    Usage: ./build_agent x.x.x {platform}

    Example: ./build_agent 0.7.1 deb
"""

import os
import re
import sys
import shutil
import subprocess

BUILD_DIRS = ['../bin', '../daemon', '../plugins', '../src', '../deps']
BUILD_FILES = [
    '../agent.py', '../watcher_mac.py', '../agent.config', 'agent_utils'
]
INSTALL_SCRIPT = 'agent_utils'

# No longer necessary as the install script can run on its own for
# the oldest platform we support.
#PLATFORM_SHEBANG = {
#    'mac': '#!agent/deps/mac/Python-2.7.5/bin/python',
#    #'deb' : '#!agent/deps/deb/Python-2.7.5/bin/python',
#    'deb': '#!/usr/bin/python',
#    'rpm': '#!agent/deps/rpm/Python-2.7.5/bin/python',
#    'rpm6': '#!agent/deps/rpm6/Python-2.7.5/bin/python',
#    'rpm-32': '#!agent/deps/rpm-32/Python-2.7.5/bin/python',
#    'rpm6-32': '#!agent/deps/rpm6-32/Python-2.7.5/bin/python'
#}

COMPILED_PYTHON_PATHS = {
    'mac': 'agent/deps/mac/Python-2.7.5/',
    #'deb': 'agent/deps/deb/Python-2.7.5/',
    'rpm5_64': 'agent/deps/rpm/Python-2.7.5/',
    'rpm6_64': 'agent/deps/rpm6/Python-2.7.5/',
    'rpm5_32': 'agent/deps/rpm-32/Python-2.7.5/',
    'rpm6_32': 'agent/deps/rpm6-32/Python-2.7.5/'
}


def del_existing_dir(dir_name):
    if os.path.exists(dir_name):
        print 'Removing existing dir: {0}'.format(dir_name)

        shutil.rmtree(dir_name)

        print '{0} removed.'.format(dir_name)


def copy_dirs(dest):
    global BUILD_DIRS

    for dir in BUILD_DIRS:
        shutil.copytree(dir, os.path.join(dest, os.path.basename(dir)))


def copy_files(dest):
    global BUILD_FILES

    for file in BUILD_FILES:
        shutil.copy(file, dest)


def remove_compiled_pythons(agent_pkg_dir, platform):
    global COMPILED_PYTHON_PATHS

    for py_path in COMPILED_PYTHON_PATHS:
        if platform != py_path:
            shutil.rmtree(
                os.path.join(agent_pkg_dir, COMPILED_PYTHON_PATHS[py_path])
            )


def modify_config_version(config_path, version):
    f = open(config_path, 'r')
    try:
        file_content = f.read()
    finally:
        f.close()

    f = open(config_path, 'w')
    try:
        new_content = file_content.splitlines()

        for line in new_content:
            if re.match('^version =.*', line):
                line_position = new_content.index(line)

                new_content[line_position] = 'version = {0}'.format(version)

        f.write('\n'.join(new_content))

    finally:
        f.close()


def mac_build(build_name, folder_name):
    dmg_name = build_name + '.dmg'

    cmd = [
        '/usr/bin/hdiutil',
        'create',
        dmg_name,
        '-srcfolder',
        folder_name,
        '-ov'
    ]
    subprocess.call(cmd)


def create_zip(build_name, folder_name):
    zip_name = build_name + '.zip'

    cmd = ['zip', '-r', zip_name, folder_name]
    subprocess.call(cmd)


def create_tar(build_name, folder_name):
    tar_name = build_name + '.tar.gz'

    cmd = ['tar', '-czf', tar_name, folder_name]
    subprocess.call(cmd)


def deb_build(build_name, folder_name):
    create_tar(build_name, folder_name)


def rpm_build(build_name, folder_name):
    create_tar(build_name, folder_name)


SUPPORTED_PLATFORMS = {
    'mac': mac_build,
    'deb': deb_build,
    'rpm5_64': rpm_build,
    'rpm6_64': rpm_build,
    'rpm5_32': rpm_build,
    'rpm6_32': rpm_build
}


def build(version, platform):
    global INSTALL_SCRIPT
    global SUPPORTED_PLATFORMS

    agent_pkg_dir = 'VFAgent_' + version.replace('.', '_')

    del_existing_dir(agent_pkg_dir)

    os.makedirs(agent_pkg_dir, 0755)

    agent_dir_path = os.path.join(agent_pkg_dir, 'agent')
    os.makedirs(agent_dir_path, 0755)

    print 'Copying needed directories.'
    copy_dirs(agent_dir_path)
    print 'Copying needed files.'
    copy_files(agent_dir_path)

    print 'Copying install script.'
    shutil.copy(INSTALL_SCRIPT, os.path.join(agent_pkg_dir, 'install'))

    print 'Removing unnecessary compiled pythons.'
    remove_compiled_pythons(agent_pkg_dir, platform)

    print 'Setting agent version.'
    modify_config_version(
        os.path.join(agent_dir_path, 'agent.config'), version
    )

    print 'Creating final product.'
    SUPPORTED_PLATFORMS[platform](
        agent_pkg_dir + '-' + platform, agent_pkg_dir
    )


def main():
    global SUPPORTED_PLATFORMS

    version = sys.argv[1]
    platform = sys.argv[2]

    if version.count('.') != 2:
        print 'Please follow the version format "x.x.x"'
        sys.exit(1)

    if platform == 'all':
        for platform in SUPPORTED_PLATFORMS:
            build(version, platform)
    elif platform in SUPPORTED_PLATFORMS:
        build(version, platform)
    else:
        print '{0} is not supported.'.format(platform)
        print 'Supported platforms are: {0}'.format(SUPPORTED_PLATFORMS.keys())
        sys.exit(1)


if __name__ == '__main__':
    main()
